--- 
- !ruby/object:Rubber::Configuration::InstanceItem 
  domain: interviewer.in
  external_host: ec2-23-22-98-131.compute-1.amazonaws.com
  external_ip: 23.22.98.131
  image_id: ami-4dad7424
  image_type: t1.micro
  instance_id: i-0a4c5272
  internal_host: ip-10-205-9-165.ec2.internal
  internal_ip: 10.205.9.165
  name: staging
  platform: linux
  roles: 
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: web
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: haproxy
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: app
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: passenger
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: apache
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: db
    options: 
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: mysql
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: mysql_master
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: collectd
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: monit
    options: {}

  root_device_type: ebs
  security_groups: 
  - hrcoffee_production_default
  - hrcoffee_production_web
  - hrcoffee_production_staging
  - hrcoffee_production_haproxy
  - hrcoffee_production_app
  - hrcoffee_production_passenger
  - hrcoffee_production_apache
  - hrcoffee_production_db
  - hrcoffee_production_mysql
  - hrcoffee_production_mysql_master
  - hrcoffee_production_collectd
  - hrcoffee_production_monit
  zone: us-east-1b
- volumes: {}

  static_ips: {}

